[package]
name = "rrbg"
version = "0.1.0"
authors = ["Evan Stoll <evanjsx@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
envy = "0.3.3"
glob = "0.2.11"
serde_derive = "1.0.82"
serde = "1.0.82"
rayon = "1.0.3"
imagesize = "0.6.0"
log = "0.4.6"
env_logger = "0.6.0"
dict = "0.1.5"
rand = "0.6.1"
wallpaper = "2.0.0"

[dependencies.x11]
version = "2.18.1"
default-features = true
features = ["xlib"]

[profile.release]
opt-level = "z"
lto = "thin"
